# Generated by Django 5.2.4 on 2025-07-29 01:22

import django.db.models.deletion
import institutionalResearchAgenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalResearchAgenda',
            fields=[
                ('ira_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=institutionalResearchAgenda.models.upload_to_ira)),
                ('rationale', models.TextField()),
                ('role_of_rmo', models.TextField()),
                ('objectives', models.TextField()),
                ('update_process', models.TextField()),
                ('framework_description', models.TextField()),
                ('date_covered', models.CharField(default='2025–2030', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('ira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_areas', to='institutionalResearchAgenda.institutionalresearchagenda')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('key_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='institutionalResearchAgenda.keyresearcharea')),
            ],
        ),
        migrations.CreateModel(
            name='PriorityTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('details', models.TextField(blank=True, null=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='institutionalResearchAgenda.researchtheme')),
            ],
        ),
    ]
