# Generated by Django 5.2.4 on 2025-07-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='activityphoto',
            name='id',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='activityphoto',
            name='activity_photo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
