# Generated by Django 5.2.4 on 2025-07-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_activity_id_remove_activityphoto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
