# Generated by Django 5.2.4 on 2025-08-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_end_time_activity_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
