# Generated by Django 5.2.4 on 2025-08-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='size',
            field=models.BigIntegerField(),
        ),
    ]
