# Generated by Django 5.2.4 on 2025-08-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_title_resource_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
