# Generated by Django 5.2.4 on 2025-07-11 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, max_length=600)),
                ('description', models.TextField(max_length=8000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementPhoto',
            fields=[
                ('announcement_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='announcements/')),
                ('is_cover', models.BooleanField(default=False)),
                ('announcement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='announcements.announcement')),
            ],
        ),
    ]
