# Generated by Django 5.2.4 on 2025-07-11 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='author_id',
        ),
    ]
