# Generated by Django 5.2.4 on 2025-07-18 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_remove_proponent_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=600)),
                ('authors', models.TextField(blank=True, max_length=600)),
                ('email', models.TextField(blank=True, max_length=600)),
                ('abstract', models.TextField(max_length=5000)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.college')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleFiles',
            fields=[
                ('article_file_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_path', models.FileField(upload_to='articles/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleFiles', to='articles.articles')),
            ],
        ),
    ]
