# Generated by Django 5.2.4 on 2025-07-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='articles',
            name='authors',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='articles',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
