# Generated by Django 5.2.4 on 2025-07-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_keywords_alter_articles_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='email',
        ),
        migrations.AddField(
            model_name='articles',
            name='emails',
            field=models.JSONField(default=list),
        ),
    ]
