# Generated by Django 5.2.4 on 2025-07-11 02:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('base', '0006_remove_proponent_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('eval_id', models.AutoField(primary_key=True, serialize=False)),
                ('presentation', models.IntegerField()),
                ('content', models.IntegerField()),
                ('organization', models.IntegerField()),
                ('mastery', models.IntegerField()),
                ('remarks', models.CharField(max_length=2500)),
                ('evaluatorName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FormClearance',
            fields=[
                ('form_clearance_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_completed', models.CharField(max_length=255)),
                ('year_completed', models.CharField(max_length=255)),
                ('date_of_article_submission', models.DateField(default=datetime.date.today)),
                ('article_code_num', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='FormSchedule',
            fields=[
                ('form_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('proposal_date', models.DateField()),
                ('proposal_time', models.TimeField()),
                ('proposal_place', models.CharField(max_length=1000)),
                ('final_defense_date', models.DateField()),
                ('final_defense_time', models.TimeField()),
                ('final_defense_place', models.CharField(max_length=1000)),
                ('date_reviewed_by_chairman', models.DateField()),
                ('date_of_data_gathering', models.DateField()),
                ('place_of_data_gathering', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('form_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('formName', models.CharField(max_length=500)),
                ('formDescription', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='FormApproval',
            fields=[
                ('form_approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='FormPanel',
            fields=[
                ('form_panel_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.date.today)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.college')),
                ('cra_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.collegeresearchagenda')),
                ('eval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.evaluationcriteria')),
                ('ira_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.institutionalresearchagenda')),
                ('student_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('form_approval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formapproval')),
                ('form_clearance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formclearance')),
                ('form_panel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formpanel')),
                ('form_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formschedule')),
                ('form_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formtype')),
            ],
        ),
        migrations.CreateModel(
            name='Proponent',
            fields=[
                ('proponent_id', models.AutoField(primary_key=True, serialize=False)),
                ('proposal_receipt_num', models.CharField(max_length=500)),
                ('defense_receipt_num', models.CharField(max_length=500)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
                ('thesis_title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.thesistitle')),
            ],
        ),
        migrations.CreateModel(
            name='ProposedTitle',
            fields=[
                ('proposed_title_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=500)),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.college')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
            ],
        ),
    ]
