# Generated by Django 5.2.4 on 2025-07-29 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('institutionalResearchAgenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='ira_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutionalResearchAgenda.institutionalresearchagenda'),
        ),
    ]
