# Generated by Django 5.2.4 on 2025-07-06 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_usertype_faculty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='college_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.college'),
        ),
        migrations.AlterField(
            model_name='account',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.course'),
        ),
    ]
