# Generated by Django 5.2.4 on 2025-07-29 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_proponent_account_id_and_more'),
        ('forms', '0002_alter_form_ira_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstitutionalResearchAgenda',
        ),
    ]
